### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chrisreddington** [CloudWithChris/hugo-creator#3]
Definition of done:

- [x] Include an image which shows the status of the latest build
- [x] Include an image which shows the status of the latest release
  - [x] #4  [Required dependency before completing above issue]
- [x] Include a link to an example site deployment (https://hugo-creator.cloudwithchris.com/)
  - [x] #4 [Required dependency before completing above issue]
- [ ] Include details on installation steps (similar to how other Hugo themes are installed)
- [x] Include a section on usage, which contains:
  - [x] An example 'clean' output of the Site Config settings
  - [x] A table showcasing the Field Name, Required, Description and Example (example of this on my other theme [here](https://github.com/chrisreddington/hugo-community/blob/main/REFERENCE.md)
  - [x] A section explaining the archetypes of the site, similar to the experience [here](https://github.com/chrisreddington/hugo-community/blob/main/REFERENCE.md#archetypes)
- [x] Include a section on getting started with contributing, which links to the [contributing doc](https://github.com/CloudWithChris/hugo-creator/blob/main/contributing.md).
  - [x] #5  [Required dependency before completing above issue]
- [x] Include a section on the license being used, which links to the [license page](https://github.com/CloudWithChris/hugo-creator/blob/main/LICENSE).
- [x] Include a set of example sites that are being used, as well as a recommendation to add your site to the list if you use the theme.
- [ ] Ensure that the readme meets the requirements to submit the theme to Hugo centrally (https://github.com/gohugoio/hugoThemesSiteBuilder/blob/main/README.md#readmemd)

**Comment by SaintJul** [comment]
Hi Chris, could I help with the readme?

**Comment by chrisreddington** [comment]
> Hi Chris, could I help with the readme?

Absolutely, thanks for the interest! I'll get the initial description updated with some of the items that we'll need to add :)

**Comment by chrisreddington** [comment]
@SaintJul - I have added some pointers to the initial post. It had some dependencies, which I think I've now resolved. Let me know if there's anything I can do to help :)

**Comment by chrisreddington** [comment]
Hey @SaintJul, I've made quite a few changes, which should make the readme creation easier :) I think we're now at an MVP stage for the actual theme, so the remaining outstanding item for an initial release would be the Readme.

Please shout if there's anything that you need from me at all, and thanks again for taking the time to contribute. :)

**Comment by SaintJul** [comment]
Thank you so much and sorry for the delay.

**Comment by chrisreddington** [comment]
> Thank you so much and sorry for the delay.

Not at all, nothing to be sorry for! I greatly welcome the time you're spending on the contribution - Thank you :)

**Comment by SaintJul** [comment]
https://github.com/SaintJul/hugo-creator Sorry, I thought I posted the merge request to your repo. What do you think?

**Comment by chrisreddington** [comment]
Thanks again for the contribution @SaintJul! I took a fork of your version, and then made some adjustments (e.g. adding in the reference material from my work on the archetypes, etc.)

I've now merged this in, and it's available on the main branch. Thank you again for taking the time and contributing! :)

**Comment by SaintJul** [comment]
Thank you for allowing me to contribute!
